### ISSUE TITLE
Wrong md5 result

### ISSUE THREAD

**Issue by sinhpn92** [weizongwei5/EncryptJni#1]
I have get md5 result on galaxy s7 device. What's wrong here?

**Comment by BruceWind** [comment]
what's wrong?I do not understand what you are experiencing.

**Comment by zhangniuniu** [comment]
dou you find the solution  in diffenrent arm? @sinhpn92

**Comment by sinhpn92** [comment]
@zhangniuniu , @weizongwei5 
This is my solution:
[https://stackoverflow.com/questions/42303607/returning-wrong-md5-hash-in-jni](https://stackoverflow.com/questions/42303607/returning-wrong-md5-hash-in-jni)

**Comment by zhangniuniu** [comment]
thanks,I have seen it，but I have not tried yet @sinhpn92

**Comment by BruceWind** [comment]
sorry，long time ago.  
[fixcommit:ad27a55b001c9ecbaa16b3ccdf3004135e7ef250](https://github.com/weizongwei5/EncryptJni/blob/ad27a55b001c9ecbaa16b3ccdf3004135e7ef250/encryptlib/src/main/jni/md5.h)
